### ISSUE TITLE
Migration issue from BC to TP with income_recipients

### ISSUE THREAD

**Issue by jensamberg** [alis-is/tezpay#1]
Migration issue from BC to TP with income_recipients.

With BC the bonds or fees income_recipients has a granularity of 100 %.
As far have investagted TP interp 100 % as 1. So if TP migrates a BC config.hjson it should migrate 100 % to 1 and
1% to 0.01.

**Comment by cryi** [comment]
Hi. Should be fixed in [0.0.20](https://github.com/alis-is/tezpay/releases/tag/0.0.20-alpha) and newer versions.
